services:
  db:
    image: postgis/postgis:16-3.4
    container_name: tosca-db
    env_file:
      - .env.dev

    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_SUPERUSER}
      POSTGRES_PASSWORD: ${PG_SUPERPASS}

      # GeoServer database role and schemas used by the init script.
      PG_GS_USER: ${PG_GS_USER}
      PG_GS_PASSWORD: ${PG_GS_PASSWORD}
      PG_SCHEMA_GEOSERVER: ${PG_SCHEMA_GEOSERVER}
      PG_SCHEMA_GIS: ${PG_SCHEMA_GIS}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./docker/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${PG_SUPERUSER} -d ${PG_DATABASE} -h 127.0.0.1 -p 5432",
        ]
      interval: 5s
      timeout: 3s
      retries: 30
    restart: unless-stopped

  geoserver:
    build:
      context: .
      dockerfile: docker/Dockerfile
      platforms:
        - linux/arm64
        # - linux/amd64 # Intel/AMD (CI, servers) – enable for x86_64 builds
      args:
        GEOSERVER_VERSION: ${GEOSERVER_VERSION}
    image: dcs-geoserver:${GEOSERVER_VERSION} #dev purpose local image name
    container_name: tosca-geoserver
    env_file:
      - .env.dev
    ports:
      - "${GEOSERVER_PORT}:8080"
    volumes:
      - geoserver_data:/geoserver_data/data
      # - ./docker/geoserver-init:/geoserver-init:ro
      - /Users/hsadmin:/mnt/home
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:8080/geoserver/web"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped
volumes:
  pg_data:
  geoserver_data:
