services:
  db:
    image: postgis/postgis:16-3.4
    container_name: tosca-db
    env_file:
      - .env.prod
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_SUPERUSER}
      POSTGRES_PASSWORD: ${PG_SUPERPASS}

      PG_API_USER: ${PG_API_USER}
      PG_API_PASSWORD: ${PG_API_PASSWORD}
      PG_GS_USER: ${PG_GS_USER}
      PG_GS_PASSWORD: ${PG_GS_PASSWORD}
      PG_SCHEMA_API: ${PG_SCHEMA_API}
      PG_SCHEMA_GEOSERVER: ${PG_SCHEMA_GEOSERVER}
      PG_SCHEMA_GIS: ${PG_SCHEMA_GIS}
    ports:
      - "${POSTGRES_HOST_PORT:-5438}:${POSTGRES_CONTAINER_PORT:-5432}"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./docker/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${PG_SUPERUSER} -d ${PG_DATABASE} -h 127.0.0.1 -p ${POSTGRES_CONTAINER_PORT:-5432}",
        ]
      interval: 5s
      timeout: 3s
      retries: 30

    restart: unless-stopped

  geoserver:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        GEOSERVER_VERSION: ${GEOSERVER_VERSION:-2.28.3}
        DEFAULT_OFFICIAL_PLUGINS: ${OFFICIAL_PLUGINS:-mbstyle,vectortiles}
        DEFAULT_COMMUNITY_PLUGINS: ${COMMUNITY_PLUGINS-}
        BUILD_JDBC_PLUGINS: ${BUILD_JDBC_PLUGINS:-false}
    image: tosca-geoserver-local31:${GEOSERVER_VERSION:-2.28.3}
    container_name: tosca-geoserver
    env_file:
      - .env.prod
    environment:
      GEOSERVER_SECURITY_MODE: ${GEOSERVER_SECURITY_MODE:-default}
      GEOSERVER_ENABLE_JDBC_ROLE: ${GEOSERVER_ENABLE_JDBC_ROLE:-false}
      GEOSERVER_ENABLE_JDBC_AUTH: ${GEOSERVER_ENABLE_JDBC_AUTH:-false}
      GEOSERVER_ENABLE_JDBC_CONFIG: ${GEOSERVER_ENABLE_JDBC_CONFIG:-false}
      GEOSERVER_JDBC_EXTRA_ROLES: ${GEOSERVER_JDBC_EXTRA_ROLES:-}
      GEOSERVER_JDBC_CONFIG_IMPORT: ${GEOSERVER_JDBC_CONFIG_IMPORT:-false}
      ENABLE_JDBC_LOGIN: ${ENABLE_JDBC_LOGIN:-false}
      ENABLE_JDBC_CONFIG: ${ENABLE_JDBC_CONFIG:-false}
      OFFICIAL_PLUGINS: ${OFFICIAL_PLUGINS:-mbstyle,vectortiles}
      COMMUNITY_PLUGINS: ${COMMUNITY_PLUGINS-}
      BUILD_JDBC_PLUGINS: ${BUILD_JDBC_PLUGINS:-false}
    ports:
      - "${GEOSERVER_HOST_PORT:-8080}:${GEOSERVER_CONTAINER_PORT:-8080}"
    volumes:
      - geoserver_data:/geoserver_data/data
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:${GEOSERVER_CONTAINER_PORT:-8080}/geoserver/web"]
      interval: 10s
      timeout: 5s
      retries: 10

    restart: unless-stopped
volumes:
  pg_data:
  geoserver_data:
