services:
  db:
    image: postgis/postgis:16-3.4
    container_name: tosca-db
    env_file:
      - .env.prod
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_SUPERUSER}
      POSTGRES_PASSWORD: ${PG_SUPERPASS}

      # initdb script'lerin kullanıyorsa bunları da geçiyoruz:
      PG_API_USER: ${PG_API_USER}
      PG_API_PASSWORD: ${PG_API_PASSWORD}
      PG_GS_USER: ${PG_GS_USER}
      PG_GS_PASSWORD: ${PG_GS_PASSWORD}
      PG_SCHEMA_API: ${PG_SCHEMA_API}
      PG_SCHEMA_GEOSERVER: ${PG_SCHEMA_GEOSERVER}
      PG_SCHEMA_GIS: ${PG_SCHEMA_GIS}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./docker/initdb:/docker-entrypoint-initdb.d
    restart: unless-stopped

  geoserver:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        GEOSERVER_VERSION: ${GEOSERVER_VERSION:-2.27.2}
    image: tosca-geoserver-local:${GEOSERVER_VERSION:-2.27.2}
    container_name: tosca-geoserver
    env_file:
      - .env.prod
    ports:
      - "${GEOSERVER_PORT}:8080"
    volumes:
      - geoserver_data:/geoserver_data/data
      - /LOCAL_:/mnt/home
    restart: unless-stopped
volumes:
  pg_data:
  geoserver_data:
